### ISSUE TITLE
[Bug] Authorization Process Fails During Tool Usage

### ISSUE THREAD

**Issue by isma221** [ArcadeAI/arcade-mcp#637]
When attempting to use the tool that requires authorization, an authorization error occurs despite providing valid credentials.

I’m using the exact code provided in the Arcade documentation:
https://docs.arcade.dev/en/home/langchain/user-auth-interrupts

**Comment by EricGustin** [comment]
Hi @isma221 thanks for the report. I am actively looking into this

**Comment by EricGustin** [comment]
@isma221 The documentation at https://docs.arcade.dev/en/home/langchain/user-auth-interrupts has been fixed.

**Comment by isma221** [comment]
@EricGustin The issue still persists. I’m still facing the authorization error, and I’m using the exact same code provided in the documentation. Maybe there’s an issue with the token exchange process.

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/6c945cf9-4747-4baa-9e32-6c53102f724a" />

**Comment by EricGustin** [comment]
@isma221 can you confirm that you are using the email that is associated with your Arcade.dev account as the `user_id`? Also, are you following the Python or JavaScript example?

**Comment by isma221** [comment]
I'm following the Python example. I tried using other codes from your documentation, but I still faced the authorization error. I also tried logging in with both of my emails, my academic email (i211744@nu.edu.pk) and my personal email (isma.ahsan221@gmail.com).

**Comment by isma221** [comment]
> [@isma221](https://github.com/isma221) can you confirm that you are using the email that is associated with your Arcade.dev account as the `user_id`? Also, are you following the Python or JavaScript example?

yes i am using email which is associated with arcade.dev account.  I am following python example.

**Comment by EricGustin** [comment]
@isma221 can you please retry. If it fails once again, then please share a screenshot of both the flow_id in the URL query params & expand the developer info

**Comment by isma221** [comment]
<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/1a14dfa1-9132-436d-9f84-10ea3f89ac82" />
I'm still facing this error. I’ve tried it on both Mac and Windows, but the problem still persists.

**Comment by EricGustin** [comment]
Hi @isma221 I checked logs on my end and it looks like you need to replace `'{arcade_user_id}'` with your email ending in `...221@gmail.com`
